# -*- coding: utf-8 -*-
"""exercise 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZwNwGyo8W3IskQOiQJSP-2m5qAjR1-l
"""

# Exercise 07:
import pandas as pd
dict={'name':["Sandeep","mahi","Umesh"],
'age':["19","21","22"]}
a=pd.DataFrame(dict,index=[True,False,True])
print(a)

import pandas as pd
dict={'name':["Sandeep","mahi","Umesh"],
'age':["19","21","22"]}
a=pd.DataFrame(dict,index=[True,False,True])
print(a.loc[True])

import numpy as np
arr=np.arange(16)
print("The Original array is:\n",arr)
arr=np.arange(16).reshape(2,8)
print("\nreshapedarray: \n",arr)
arr=np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)