# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehMcxM05zcmzBDoQVeuiDN4ypJ5bIPeC
"""

y=['sandeep','singh']
df=pd.DataFrame(y)
print(df)

a=pd.Series(['Python','C','C++'])
a.map({'C':'HTML'})

# Exercise :- 01
import pandas as pd
import numpy as np
a=np.array(['S','a','n','d','e','e','p'])
b=pd.Series(a)
print(b)

p=pd.Series(["sun","mon","tue"],name="days")
p.to_frame()

import matplotlib.pyplot as plt
user_name=['sandeep','umesh','mahi']
id=[101,102,103]
user_name_series=pd.Series(user_name)
id_Series=pd.Series(id)
frame={'user_name':user_name_series,'id':id_Series}
result=pd.DataFrame(frame)
print(result)

# Exercise :- 02
# Create empty data frame
df=pd.DataFrame()
print(df)

# Create DataFrame using List
y=['Sandeep','Jaat']
df=pd.DataFrame(y)
print(df)

# Create DataFrame from Dict of List
a={'id':[100,101,102],'Course':['B.Tech','B.A','M.Tech']}
df=pd.DataFrame(a)
print(df)

# Create DataFrame from Dict of Series and also knowing datatype
a={'one': pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),
    'two': pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
D=pd.DataFrame(a)
print(D)
print(D['one'])

# Adding new columns to an existing DataFrame
a={'one': pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),
    'two': pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(a)
print("Add new column by passing series")
df['three']=pd.Series([60,80,100,120,140],index=['a','b','c','d','e'])
print(df)
print("Add new column using existing DataFrame columns")
df['four']=df['one']+df['three']
print(df)

# Column Deletion:
a={'one': pd.Series([1,2,3],index=['a','b','c']),
    'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(a)
print("The DataFrame:")
print(df)
print("Delete first column:")
del df['one']
print(df)
print("Delete second column:")
df.pop('two')
print(df)

# finding location
a={'one': pd.Series([1,2,3],index=['a','b','c']),
    'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(a)
print(df.loc['c'])

# finding index location
a={'one': pd.Series([1,2,3],index=['a','b','c']),
    'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(a)
print(df.iloc[2])

# Slicing of rows
a={'one': pd.Series([1,2,3],index=['a','b','c']),
    'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(a)
print(df[1:4])

# Addition of rows
d1=pd.DataFrame([[12,13],[14,15]],columns=['a','b'])
d2=pd.DataFrame([[21,22],[23,24]],columns=['a','b'])
d1=d1.append(d2)
print(d1)

# Deletion of rows
d1=pd.DataFrame([[12,13],[14,15]],columns=['a','b'])
d2=pd.DataFrame([[21,22],[23,24]],columns=['a','b'])
d1=d1.append(d2)
d1=d1.drop(0)